### ISSUE TITLE
Error in Multiple columns example

### ISSUE THREAD

**Issue by mikbox74** [unclead/yii2-multiple-input#17] opened 2015-07-24 12:10 UTC
https://github.com/unclead/yii2-multiple-input/blob/master/docs/multiple_columns.md
This validation example not works
```php
$key = $attribute . '[' . $index . '][label]';
$this->addError($key, $error);
```
The $error not displays.
I guess it is possible but requires impruvement within the widget code.

**Comment by unclead** [comment] 2015-07-24 15:51
i'll check the example documentation but here is screen from my test app: http://prntscr.com/7wi131 
As you can see validation works fine. Please enter your code, so I checked it

**Comment by mikbox74** [comment] 2015-07-24 16:03
Eugene, thank you for answer. Here is my code.
Model:
```php
namespace frontend\widgets\menu;

use Yii;
use yii\validators\RequiredValidator;

class Configuration extends \common\models\WidgetsConfig
{
    public $items;
    //public $title;
    public function rules()
    {
        return [
            ['items', 'validateItems'],
        ];
    }
    public function init()
    {
        parent::init();
    }
    
    public function attributeLabels()
    {
        return [
            'items' => 'Пункты меню',
        ];
    }
    
    public function validateItems($attribute)
    {
        $requiredValidator = new RequiredValidator();
        $requiredValidator->message = 'Необходимо заполнить поле.';

        foreach($this->$attribute as $index => $row) {
            $error = null;
            $requiredValidator->validate($row['label'], $error);
            if (!empty($error)) {
                $key = $attribute . '[' . $index . '][label]';
                $this->addError($key, $error);
            }
        }
    }
    public function rolesList()
    {
        return Yii::$app->authManager->getRoles();
    }
}
```
form:
```php
use unclead\widgets\MultipleInput;
use yii\helpers\ArrayHelper;

$roles = Yii::$app->authManager->getRoles();

echo $form->field($model, 'items')->widget(MultipleInput::className(), [
    'columns' => [
        [
            'name'  => 'label',
            'title' => 'Название',
        ],
        [
            'name'  => 'url',
            'title' => 'Ссылка',
            'defaultValue' => '/',
        ],
        [
            'name'  => 'access',
            'type'  => 'checkboxList',
            'title' => 'Доступ',
            'items' => ArrayHelper::map($roles, 'name', 'description'),
            'options' => [
                'item' => function ($index, $label, $name, $checked, $value) {
                   $render = '<div class="checkbox">
                      <label>
                        <input type="checkbox"'.($checked?' checked':'').' name="'.$name.'" value="'.$value.'">
                         '.$label.'
                      </label>
                    </div>';
                    return $render;
                }
            ],
        ]
    ]
 ])->hint('Если ни одна роль не отмечена, то пункт меню смогут увидеть все пользователи');
```
May be it not works because the model extends base\Model, not ActiveRecord?

**Comment by unclead** [comment] 2015-07-24 16:14
it not works because widget uses Html helper for rendering the inputs. 
I'll try to use your solution with some modification for fixing this bug

**Comment by unclead** [comment] 2015-07-24 16:35
@mikbox74  Try to update to latest revision. I adapted your code. Let me know if all is correct

**Comment by mikbox74** [comment] 2015-07-24 19:14
I try it with example above. Div.help-block.help-block-error appears but it is empty and field not highlighted. Obviously you forget to put errors from model into the div and add class has-error to div.form-control.

**Comment by unclead** [comment] 2015-07-25 12:23
You use form without Ajax validation. Am I right? I forgot about this use case

Отправлено со смартфона Sony Xperia™

Пользователь Michail <notifications@github.com> писал:

**Comment by mikbox74** [comment] 2015-07-25 12:40
Yes, right.

2015-07-25 16:23 GMT+04:00, Eugene Tupikov <notifications@github.com>:
> You use form without Ajax validation. Am I right? I forgot about this use
> case
>
> Отправлено со смартфона Sony Xperia™
>
> Пользователь Michail <notifications@github.com> писал:
>
>>I try it with example above. Div.help-block.help-block-error appears but it
>> is empty and field not highlighted. Obviously you forget to put errors
>> from model into the div and add class has-error to div.form-control.
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/unclead/yii2-multiple-input/issues/17#issuecomment-124649383
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/unclead/yii2-multiple-input/issues/17#issuecomment-124840223


-- 
-------
С уважением, Михаил

**Comment by unclead** [comment] 2015-07-27 03:57
Fixed via Please check it again and let me know if the issue reproduced
@mikbox74 please check it again. You can get more detail in multiple columns example

**Closed by unclead** 2015-07-27 03:57 UTC

**Comment by mikbox74** [comment] 2015-07-28 07:08
All works fine. Thank you for this incredible widget!

**Comment by daniroyo** [comment] 2020-11-01 19:45
Sorry for reopen issue, close if you think it is better to create new one.

First of all, thanks a lot for such as incredible widget, it fits my need perfectly.

I notice errors works fine but error messages are not show. Is it that for missconfiguration of mine or is it an expected behaviour?

Ressume: Errors are highlighted, but error messages are not shown

**Comment by unclead** [comment] 2020-11-02 11:01
@daniroyo create a new issue with the code example to reproduce your case

**Comment by daniroyo** [comment] 2020-11-02 18:46
Sorry, but I finally found the way to show the error, using attribute "enableError" on Column definition like follows.

´´´
        <?= $form->field($model, 'users')->widget(MultipleInput::class, [
                // 'max' => 4,
                'addButtonPosition' => [
                    MultipleInput::POS_FOOTER,
                    MultipleInput::POS_HEADER,
                ],
                'columns' => [
                    [
                        'name'  => 'username',
                        'title' => Yii::t('app', 'Username'),
                        **'enableError' => true,**
                        'options' => [
                            'class' => '',
                        ],
                    ],
                ]
            ]);
            ?>
´´´

**Comment by unclead** [comment] 2020-11-03 09:50
this option is covered in the [documentation](https://github.com/unclead/yii2-multiple-input/wiki/Configuration#column-options) 😄
