### ISSUE TITLE
daterangepicker is not defined TabularInput

### ISSUE THREAD

**Issue by ered15** [unclead/yii2-multiple-input#225] opened 2018-08-02 18:12 UTC
Hi,i'm getting this error `ReferenceError: daterangepicker_9859142c is not defined` when using `'type'  => DateRangePicker::classname(),` in a column inside `TabularInput::widget()` anyone know why?

**Comment by ered15** [comment] 2018-08-02 18:35
Think is a similar issue to: https://github.com/unclead/yii2-multiple-input/issues/215 just to be clear the issue only happens when using TabularInput::widget()

**Comment by unclead** [comment] 2018-10-02 08:29
duplicate of #215

**Closed by unclead** 2018-10-02 08:29 UTC
