### ISSUE TITLE
Navbar Dropdown Menu is not working after using MultipleInput widget

### ISSUE THREAD

**Issue by rahulk-k** [unclead/yii2-multiple-input#47] opened 2015-10-14 04:59 UTC
Hi,
   I am using my custom bootstrap theme and your widget in the bootstrap form.Its working fine.but problem is that when i click on navbar dropdown menu then its not opening my dropdown menu.but dropdown menu is working  when i removes your widget.
![capture](https://cloud.githubusercontent.com/assets/10880236/10475210/6b19104a-725e-11e5-8445-6866644abba1.PNG)

**Comment by unclead** [comment] 2015-10-14 05:56
Do you have any js errors in console log?

**Comment by rahulk-k** [comment] 2015-10-14 07:28
@unclead  have not found any errors in console log.

**Comment by unclead** [comment] 2015-10-14 07:39
i'll try to reproduce but unfortunately i'm too busy on main job and cannot do it right now

**Comment by unclead** [comment] 2015-10-15 06:00
Can you give me code example? How do you use my widget?

**Comment by rahulk-k** [comment] 2015-10-15 09:12
echo $form->field($model, 'products',[
                'template' => "{label}\n<div class=\"col-md-10 col-md-offset-2\">{input}{error}</div>",
                'labelOptions' => ['class' => 'col-md-2 control-label'],
            ])->widget(MultipleInput::className(), [
               // 'limit' => 4,
                'columns' => [
                    [
                        'name'  => 'cat_id',
                        'type' => 'dropDownList',
                        'title' => 'Category',
                        'defaultValue' => "",
                      //  'enableError' => true,
                        'items' =>$d ,
                        'options'=>[
                          // 'onchange'=>'alert($(this).closest("td").next().find("select").attr("id"))',
                            'onchange'=>'
                            var d=$(this).closest("td").next().find("select").attr("id");
                            $.get("'.Yii::$app->urlManager->createUrl('site/products').'?cat_id="+$(this).val(),function(data){


                                $("#"+d).html(data);
                            });'
                            ,

                        ],
                        'headerOptions' => [
                            'style' => 'width: 20%;',
                            ]
                    ],
                    [
                        'name'  => 'product_id',
                        'type'  => 'dropDownList',
                        'title' => 'Product',
                        //'enableError' => true,
                        'items' => [
                        //    3 => 'User 3',
                        ]
                        ,'headerOptions' => [
                        'style' => 'width: 70%',
                    ]
                    ],
                    [
                        'name'  => 'quantity',
                        'type'  => 'textInput',
                        'title' => 'Qty',
                        'headerOptions' => [
                            'style' => 'width: 10%;',
                        ]
                    ],
                ]
            ])->label(false);

**Comment by rahulk-k** [comment] 2015-10-15 09:19
Here I got the problem is 
    
    <script src="/acc/assets/ab572309/jquery.js"></script>
<script src="/acc/assets/36355533/yii.js"></script>
<script src="/acc/assets/36355533/yii.validation.js"></script>
<script src="/acc/assets/89d5e7a3/js/bootstrap.js"></script>
<script src="/acc/assets/b11f7248/js/jquery.multipleInput.js"></script>
<script src="/acc/assets/36355533/yii.activeForm.js"></script>
<script src="/acc/themes/accilex/public/js/bootstrap/bootstrap.min.js"></script>
<script src="/acc/themes/accilex/public/js/scrolltopcontrol.js"></script>
<script src="/acc/themes/accilex/public/js/custom.js"></script>

When i use this widget it generates bootstrap.js file and i also added bootstrap.min.js

**Comment by unclead** [comment] 2015-10-15 16:48
Yeap, i found a place where the include files. I use Button widget from bootstrap.
https://github.com/unclead/yii2-multiple-input/blob/master/src/renderers/TableRenderer.php#L228
 I'll try to rewrite it with plain html without bootstrap widget

Or may be you know another way how we can avoid it? I need an idea :smile:

**Comment by unclead** [comment] 2015-10-17 04:47
closed via 5d8c8e269129af9002016d695eb337aa12797399

**Closed by unclead** 2015-10-17 04:47 UTC
Labels: bug

**Comment by rahulk-k** [comment] 2015-10-17 09:33
Hi @unclead Thanks for your changes.I am installing your latest version 1.2.4 ,I have not found any changes in TableRenderer.php file

**Comment by unclead** [comment] 2015-10-17 11:03
You have to use @dev flag in composr.json because i dont want to release a new version for this minor fix.
