### ISSUE TITLE
jquery.multipleInput.min.js:1 Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by aguilar16** [unclead/yii2-multiple-input#306] opened 2019-07-30 15:23 UTC
Hello, I have this problem, any idea? help me please.

`Uncaught TypeError: Cannot read property 'split' of undefined
    at f (jquery.multipleInput.min.js:1)
    at o (jquery.multipleInput.min.js:1)
    at HTMLInputElement.<anonymous> (jquery.multipleInput.min.js:1)
    at Function.each (jquery.js:367)
    at jQuery.fn.init.each (jquery.js:202)
    at jquery.multipleInput.min.js:1`

jquery.multipleInput.min.js:1

**Comment by web-develop-agat** [comment] 2019-09-24 09:22
Hello, I've got same problem. Does the solution exist?

**Comment by unclead** [comment] 2024-03-30 18:36
the issue is quite old, closing it due to inability to reproduce it on the latest widget version

**Closed by unclead** 2024-03-30 18:36 UTC
Labels: need more info
