### ISSUE TITLE
Can't work inner drag column inside another drag column

### ISSUE THREAD

**Issue by bscheshirwork** [unclead/yii2-multiple-input#312] opened 2019-08-27 14:00 UTC
If I put nested 
```
                            'type' => MultipleInput::class,
                            'options' => [
                                'sortable' => true,
```
inside to 
```
                ])->widget(MultipleInput::class, [
                    'sortable' => true,
```
the inner drag moving to outer drop zone

**Comment by unclead** [comment] 2020-11-16 13:48
according to the widget [documentation](http://johnny.github.io/jquery-sortable/#docs) that we use for sorting, it supports nested sorting. So we have to dig deeper and fix the issue

**Comment by bscheshirwork** [comment] 2020-11-16 14:22
wrong selector may be?

**Comment by unclead** [comment] 2020-11-16 17:27
I didn't investigate yet, just checked the plugin docs and found out that nested sorting is supported

**Comment by unclead** [comment] 2021-06-26 17:44
It seems that we can rewrite sorting using native drag and drop functionality (https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)

**Comment by unclead** [comment] 2024-03-30 18:34
After migration to SortableJs (see 977ca80c115fbfc1293dbe0eb811c754f6637964) the issue is not reproducible anymore. I close the issue.

**Closed by unclead** 2024-03-30 18:34 UTC
Labels: bug
